#!/usr/bin/env python3
# Generates the spatio-temporal blue noise (STBN) texture used by the
# stochastic direct lighting pass, written as a C header:
#
#     servers/rendering/renderer_rd/effects/stochastic_stbn_data.h
#
# Method: progressive least-energy insertion on a toroidal 64x64x16 domain
# (the second phase of Ulichney's void-and-cluster algorithm), with the
# separable spatial/temporal Gaussian energy of "Spatiotemporal Blue Noise
# Masks" (Wolfe et al. 2022). Each 2D slice is blue in space, and each pixel's
# sequence over the temporal axis is blue in time, which is what lets a
# renderer consume one value per frame without the low-frequency shimmer of
# independent white or even independent-per-frame blue noise.
#
# Two independent channels are generated (R drives the reservoir sampling
# chain, G drives the second random variable, e.g. area light UV sampling).
#
# Usage: python3 gen_stbn.py [output_header]

import sys

import numpy as np

SIZE_XY = 64
SIZE_T = 16
SIGMA_SPATIAL = 1.9
SIGMA_TEMPORAL = 1.1
CHANNELS = 2


def make_kernel():
    x = np.arange(SIZE_XY)
    dx = np.minimum(x, SIZE_XY - x).astype(np.float64)
    t = np.arange(SIZE_T)
    dt = np.minimum(t, SIZE_T - t).astype(np.float64)
    spatial = np.exp(-(dx[:, None] ** 2 + dx[None, :] ** 2) / (2.0 * SIGMA_SPATIAL**2))
    temporal = np.exp(-(dt**2) / (2.0 * SIGMA_TEMPORAL**2))
    kernel = temporal[:, None, None] * spatial[None, :, :]
    kernel[0, 0, 0] = 0.0  # A sample adds no energy at its own position.
    return kernel


def generate_channel(rng):
    n = SIZE_T * SIZE_XY * SIZE_XY
    kernel = make_kernel()
    energy = np.zeros((SIZE_T, SIZE_XY, SIZE_XY), dtype=np.float64)
    placed = np.zeros((SIZE_T, SIZE_XY, SIZE_XY), dtype=bool)
    ranks = np.empty((SIZE_T, SIZE_XY, SIZE_XY), dtype=np.uint32)

    # Random tie-break noise keeps the first placements from being axis-aligned.
    tie_break = rng.random((SIZE_T, SIZE_XY, SIZE_XY)) * 1e-9

    for rank in range(n):
        flat = np.where(placed, np.inf, energy + tie_break).argmin()
        t, y, x = np.unravel_index(flat, energy.shape)
        ranks[t, y, x] = rank
        placed[t, y, x] = True
        energy += np.roll(kernel, (t, y, x), axis=(0, 1, 2))
        if rank % 8192 == 0:
            print(f"  {rank}/{n}")

    # Rank -> [0;256) as uint8; every 8-bit value appears equally often.
    return (ranks.astype(np.float64) * 256.0 / n).astype(np.uint8)


def main():
    out_path = sys.argv[1] if len(sys.argv) > 1 else "servers/rendering/renderer_rd/effects/stochastic_stbn_data.h"
    channels = []
    for c in range(CHANNELS):
        print(f"Channel {c}...")
        channels.append(generate_channel(np.random.default_rng(0x5EED + c)))

    # Interleave to RG, layer-major, ready for a single RG8 texture upload.
    interleaved = np.stack(channels, axis=-1).reshape(-1)

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("/* Generated by misc/scripts/gen_stbn.py -- do not edit. */\n")
        f.write("/* 64x64x16 two-channel spatio-temporal blue noise, RG8, layer-major. */\n\n")
        f.write("#pragma once\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write(f"#define STBN_SIZE_XY {SIZE_XY}\n")
        f.write(f"#define STBN_SIZE_T {SIZE_T}\n\n")
        f.write(f"static const uint8_t STBN_RG_64X64X16[{interleaved.size}] = {{\n")
        for i in range(0, interleaved.size, 32):
            row = ",".join(str(v) for v in interleaved[i : i + 32])
            f.write("\t" + row + ",\n")
        f.write("};\n")
    print(f"Wrote {out_path} ({interleaved.size} bytes of data)")


if __name__ == "__main__":
    main()
