#!/usr/bin/env python3
"""Vendor OpenColorIO and its dependencies into Godot's thirdparty/ directory.

Godot does not run CMake, so this script performs the work CMake would normally
do at configure time:

  * copies the subset of each upstream tree that Godot actually compiles,
  * writes the headers CMake would have generated from ``*.h.in`` templates
    (``OpenColorABI.h``, ``CPUInfoConfig.h``, ``ImathConfig.h``,
    ``expat_config.h``),
  * hex-encodes OCIO's built-in ACES configs into the ``CG.cpp`` / ``Studio.cpp``
    data files that ``builtinconfigs/*Config.cpp`` include,
  * replaces ``OCIOZArchive.cpp`` with a stub so that minizip-ng is not needed
    (Godot does not support ``.ocioz`` archived configs).

Usage:
    python modules/ocio/godot_update_opencolorio.py            # download + vendor
    python modules/ocio/godot_update_opencolorio.py --src DIR  # use extracted trees in DIR

Run from anywhere; paths are resolved relative to this file.
"""

import argparse
import os
import shutil
import subprocess
import sys
import tarfile
import tempfile

# Pinned upstream versions. Keep in sync with thirdparty/README.md.
OCIO_VERSION = "2.4.2"
IMATH_VERSION = "3.1.12"
YAML_CPP_VERSION = "0.8.0"
PYSTRING_VERSION = "1.1.4"
EXPAT_VERSION = "2.6.4"

DOWNLOADS = {
    "OpenColorIO-%s" % OCIO_VERSION: "https://github.com/AcademySoftwareFoundation/OpenColorIO/archive/refs/tags/v%s.tar.gz"
    % OCIO_VERSION,
    "Imath-%s" % IMATH_VERSION: "https://github.com/AcademySoftwareFoundation/Imath/archive/refs/tags/v%s.tar.gz"
    % IMATH_VERSION,
    "yaml-cpp-%s" % YAML_CPP_VERSION: "https://github.com/jbeder/yaml-cpp/archive/refs/tags/%s.tar.gz" % YAML_CPP_VERSION,
    "pystring-%s" % PYSTRING_VERSION: "https://github.com/imageworks/pystring/archive/refs/tags/v%s.tar.gz"
    % PYSTRING_VERSION,
    "expat-%s" % EXPAT_VERSION: "https://github.com/libexpat/libexpat/releases/download/R_%s/expat-%s.tar.gz"
    % (EXPAT_VERSION.replace(".", "_"), EXPAT_VERSION),
}

MODULE_DIR = os.path.dirname(os.path.abspath(__file__))
GODOT_ROOT = os.path.normpath(os.path.join(MODULE_DIR, "..", ".."))
THIRDPARTY = os.path.join(GODOT_ROOT, "thirdparty")


def rmtree(path):
    if os.path.isdir(path):
        shutil.rmtree(path)


def copy_tree(src, dst, skip_dirs=(), skip_names=(), suffixes=None):
    """Copy src into dst, filtering by directory name, file name and suffix."""
    for root, dirs, files in os.walk(src):
        dirs[:] = [d for d in dirs if d not in skip_dirs]
        for name in files:
            if name in skip_names:
                continue
            if suffixes is not None and not name.endswith(suffixes):
                continue
            rel = os.path.relpath(os.path.join(root, name), src)
            out = os.path.join(dst, rel)
            os.makedirs(os.path.dirname(out), exist_ok=True)
            shutil.copyfile(os.path.join(root, name), out)


def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)


def download_and_extract(dest):
    """Fetch every pinned tarball into `dest` and extract it there."""
    for name, url in DOWNLOADS.items():
        if os.path.isdir(os.path.join(dest, name)):
            print("  %s already present, skipping download" % name)
            continue
        archive = os.path.join(dest, name + ".tar.gz")
        print("  fetching %s" % url)
        subprocess.run(["curl", "-sSL", "--fail", "--max-time", "300", "-o", archive, url], check=True)
        with tarfile.open(archive) as tar:
            tar.extractall(dest)
    return dest


# ---------------------------------------------------------------------------
# Generated headers (the work CMake's configure_file() would do)
# ---------------------------------------------------------------------------

GENERATED_BANNER = """// Generated by modules/ocio/godot_update_opencolorio.py from {template}.
// Do not edit by hand; edit the script and re-run it instead.
"""


def configure_file(template_path, out_path, variables, options):
    """Do what CMake's configure_file() would: expand @VAR@ and #cmakedefine.

    `variables` maps @NAME@ placeholders to their replacement text.
    `options` maps #cmakedefine / #cmakedefine01 names to a truthy value.
    """
    out_lines = []
    with open(template_path, encoding="utf-8") as f:
        for line in f.read().splitlines():
            stripped = line.strip()
            if stripped.startswith("#cmakedefine01 "):
                name = stripped.split(None, 1)[1].strip()
                if name not in options:
                    sys.exit("error: %s: no value given for #cmakedefine01 %s" % (template_path, name))
                line = "#define %s %d" % (name, 1 if options[name] else 0)
            elif stripped.startswith("#cmakedefine "):
                name = stripped.split(None, 1)[1].strip()
                if name not in options:
                    sys.exit("error: %s: no value given for #cmakedefine %s" % (template_path, name))
                line = "#define %s 1" % name if options[name] else "/* #undef %s */" % name
            for key, value in variables.items():
                line = line.replace("@%s@" % key, str(value))
            out_lines.append(line)

    text = "\n".join(out_lines) + "\n"
    if "@" in text and any("@" in line and line.count("@") >= 2 for line in out_lines):
        leftover = [line for line in out_lines if line.count("@") >= 2]
        sys.exit("error: unresolved placeholders in %s:\n  %s" % (template_path, "\n  ".join(leftover[:5])))

    banner = GENERATED_BANNER.format(template=os.path.basename(template_path))
    write(out_path, banner + text)

# SIMD is left off: OCIO's vectorised LUT kernels only matter for bulk CPU image
# processing, which Godot does at import time, and turning them off avoids
# vendoring sse2neon for arm64. The scalar paths are always compiled.
CPUINFO_CONFIG_H = """// SPDX-License-Identifier: BSD-3-Clause
// Copyright Contributors to the OpenColorIO Project.

// Generated by modules/ocio/godot_update_opencolorio.py from
// src/OpenColorIO/CPUInfoConfig.h.in. Do not edit by hand.

#if defined(__i386__) || defined(_M_IX86) || defined(__x86_64__) || defined(_M_X64)
    #define OCIO_ARCH_X86 1
#else
    #define OCIO_ARCH_X86 0
#endif

#if defined(__i386__) || defined(_M_IX86)
    #define OCIO_ARCH_X86_32 1
#else
    #define OCIO_ARCH_X86_32 0
#endif

#define OCIO_USE_SSE2NEON 0

#define OCIO_USE_SSE2  0
#define OCIO_USE_SSE3  0
#define OCIO_USE_SSSE3 0
#define OCIO_USE_SSE4  0
#define OCIO_USE_SSE42 0

#define OCIO_USE_AVX    0
#define OCIO_USE_AVX2   0
#define OCIO_USE_AVX512 0
#define OCIO_USE_F16C   0
"""

EXPAT_CONFIG_H = """/* Generated by modules/ocio/godot_update_opencolorio.py.
   Replaces the expat_config.h that autotools/CMake would produce.
   Do not edit by hand. */

#ifndef EXPAT_CONFIG_H
#define EXPAT_CONFIG_H 1

#include <stdlib.h>

/* Byte order. Godot supports little-endian targets only. */
#define BYTEORDER 1234

/* Entropy sources for the hash salt. */
#if defined(__APPLE__) || defined(__FreeBSD__) || defined(__OpenBSD__) || defined(__NetBSD__)
    #define HAVE_ARC4RANDOM_BUF 1
#elif defined(__linux__)
    #define HAVE_GETRANDOM 1
#endif

#if !defined(_WIN32)
    #define HAVE_STDINT_H 1
    #define HAVE_STDLIB_H 1
    #define HAVE_STRING_H 1
    #define HAVE_MEMMOVE 1
    #define HAVE_UNISTD_H 1
#endif

#define PACKAGE_BUGREPORT "expat-bugs@libexpat.org"
#define PACKAGE_NAME "expat"
#define PACKAGE_STRING "expat {version}"
#define PACKAGE_TARNAME "expat"
#define PACKAGE_URL ""
#define PACKAGE_VERSION "{version}"
#define VERSION "{version}"

/* Parser features OCIO relies on. */
#define XML_CONTEXT_BYTES 1024
#define XML_DTD 1
#define XML_GE 1
#define XML_NS 1

/* Godot links expat statically into the engine binary. */
#define XML_STATIC 1

#endif /* EXPAT_CONFIG_H */
"""

OCIOZ_ARCHIVE_STUB = """// SPDX-License-Identifier: BSD-3-Clause
// Copyright Contributors to the OpenColorIO Project.

// Godot replaces the upstream OCIOZArchive.cpp with this stub. The original
// implementation is the only part of OpenColorIO that depends on minizip-ng,
// and it exists purely to read and write `.ocioz` archived configs. Godot loads
// configs from plain `.ocio` files and from OpenColorIO's built-in configs, so
// the dependency is not worth vendoring. Every entry point below fails loudly
// rather than silently returning wrong colour.
//
// To restore archive support: vendor minizip-ng, drop this file, and take
// OCIOZArchive.cpp from upstream unmodified.

#include "OCIOZArchive.h"
#include "Platform.h"

namespace OCIO_NAMESPACE
{

namespace
{
constexpr char kUnsupported[] =
    "OCIOZ archives are not supported in this build of OpenColorIO. "
    "Use an unpacked .ocio config instead.";
}

void archiveConfig(std::ostream &, const Config &, const char *)
{
    throw Exception(kUnsupported);
}

std::vector<uint8_t> getFileBufferFromArchive(const std::string &, const std::string &)
{
    throw Exception(kUnsupported);
}

std::vector<uint8_t> getFileBufferFromArchiveByExtension(const std::string &, const std::string &)
{
    throw Exception(kUnsupported);
}

void getEntriesMappingFromArchiveFile(const std::string &, std::map<std::string, std::string> &)
{
    throw Exception(kUnsupported);
}

std::vector<uint8_t> CIOPOciozArchive::getLutData(const char *) const
{
    throw Exception(kUnsupported);
}

std::string CIOPOciozArchive::getConfigData() const
{
    throw Exception(kUnsupported);
}

std::string CIOPOciozArchive::getFastLutFileHash(const char *) const
{
    throw Exception(kUnsupported);
}

void CIOPOciozArchive::setArchiveAbsPath(const std::string & absPath)
{
    m_archiveAbsPath = absPath;
}

void CIOPOciozArchive::buildEntries()
{
    throw Exception(kUnsupported);
}

} // namespace OCIO_NAMESPACE
"""


def hex_encode_config(path):
    """Render a .ocio file as the comma-separated 0xNN list CMake would emit."""
    with open(path, "rb") as f:
        data = f.read()
    return ",".join("0x%02x" % b for b in data) + ",0x00"


def generate_builtin_configs(ocio_src, out_dir):
    """Write generated_include/CG.cpp and Studio.cpp from the .ocio configs."""
    template_dir = os.path.join(ocio_src, "src", "OpenColorIO", "builtinconfigs")
    configs_dir = os.path.join(template_dir, "configs")
    for template_name in sorted(os.listdir(template_dir)):
        if not template_name.endswith(".cpp.in"):
            continue
        with open(os.path.join(template_dir, template_name), encoding="utf-8") as f:
            text = f.read()
        for config_name in sorted(os.listdir(configs_dir)):
            if not config_name.endswith(".ocio"):
                continue
            stem = config_name[: -len(".ocio")]
            placeholder = "@%s@" % stem
            if placeholder in text:
                text = text.replace(placeholder, hex_encode_config(os.path.join(configs_dir, config_name)))
        if "@" in text.split("constexpr", 1)[-1]:
            sys.exit("error: unresolved placeholder left in %s" % template_name)
        write(os.path.join(out_dir, template_name[: -len(".in")]), text)
        print("    generated %s" % template_name[: -len(".in")])


# ---------------------------------------------------------------------------
# Per-library vendoring
# ---------------------------------------------------------------------------


def vendor_opencolorio(src):
    dst = os.path.join(THIRDPARTY, "opencolorio")
    rmtree(dst)
    print("  opencolorio ->", os.path.relpath(dst, GODOT_ROOT))

    copy_tree(
        os.path.join(src, "include", "OpenColorIO"),
        os.path.join(dst, "include", "OpenColorIO"),
        suffixes=(".h",),
    )
    copy_tree(
        os.path.join(src, "src", "OpenColorIO"),
        os.path.join(dst, "src", "OpenColorIO"),
        skip_dirs={"res", "configs"},
        skip_names={"CMakeLists.txt"},
        suffixes=(".h", ".cpp"),
    )
    # OCIO's core includes these two headers from src/utils via "utils/...".
    copy_tree(os.path.join(src, "src", "utils"), os.path.join(dst, "src", "utils"), suffixes=(".h",))

    # Header-only libraries that upstream bundles under ext/ and exposes as
    # CMake INTERFACE targets: xxHash (HashUtils.cpp) and a trimmed copy of
    # SampleICC (fileformats/FileFormatICC.cpp).
    for ext_name in ("xxHash", "sampleicc"):
        copy_tree(
            os.path.join(src, "ext", ext_name, "src", "include"),
            os.path.join(dst, "ext", ext_name, "include"),
            suffixes=(".h", ".hpp"),
        )

    major, minor, patch = OCIO_VERSION.split(".")
    configure_file(
        os.path.join(src, "include", "OpenColorIO", "OpenColorABI.h.in"),
        os.path.join(dst, "include", "OpenColorIO", "OpenColorABI.h"),
        variables={
            "OCIO_NAMESPACE": "OpenColorIO_v%s_%s" % (major, minor),
            "OpenColorIO_VERSION": OCIO_VERSION,
            "OpenColorIO_VERSION_RELEASE_TYPE": "",
            "OpenColorIO_VERSION_MAJOR": major,
            "OpenColorIO_VERSION_MINOR": minor,
            "OpenColorIO_VERSION_PATCH": patch,
        },
        options={},
    )
    write(os.path.join(dst, "src", "OpenColorIO", "CPUInfoConfig.h"), CPUINFO_CONFIG_H)
    write(os.path.join(dst, "src", "OpenColorIO", "OCIOZArchive.cpp"), OCIOZ_ARCHIVE_STUB)
    generate_builtin_configs(src, os.path.join(dst, "generated_include"))

    shutil.copyfile(os.path.join(src, "LICENSE"), os.path.join(dst, "LICENSE"))
    shutil.copyfile(os.path.join(src, "THIRD-PARTY.md"), os.path.join(dst, "THIRD-PARTY.md"))


def vendor_imath(src):
    dst = os.path.join(THIRDPARTY, "imath")
    rmtree(dst)
    print("  imath ->", os.path.relpath(dst, GODOT_ROOT))

    # OCIO only needs the half type, not the rest of Imath.
    needed = [
        "half.h",
        "half.cpp",
        "halfLimits.h",
        "ImathExport.h",
        "ImathNamespace.h",
        "ImathPlatform.h",
    ]
    for name in needed:
        os.makedirs(os.path.join(dst, "Imath"), exist_ok=True)
        shutil.copyfile(os.path.join(src, "src", "Imath", name), os.path.join(dst, "Imath", name))

    major, minor, patch = IMATH_VERSION.split(".")
    configure_file(
        os.path.join(src, "config", "ImathConfig.h.in"),
        os.path.join(dst, "Imath", "ImathConfig.h"),
        variables={
            "IMATH_NAMESPACE_CUSTOM": "0",
            "IMATH_NAMESPACE": "Imath",
            "IMATH_INTERNAL_NAMESPACE": "Imath_%s_%s" % (major, minor),
            "IMATH_VERSION": IMATH_VERSION,
            "IMATH_PACKAGE_NAME": "Imath %s" % IMATH_VERSION,
            "Imath_VERSION_MAJOR": major,
            "Imath_VERSION_MINOR": minor,
            "Imath_VERSION_PATCH": patch,
            "IMATH_VERSION_RELEASE_TYPE": "",
            "IMATH_LIB_VERSION": "%s.%s.%s" % (major, minor, patch),
        },
        options={
            # Godot omits the 128 KB half-to-float table; half conversion uses
            # the bit-shift algorithm instead (IMATH_HALF_NO_LOOKUP_TABLE).
            "IMATH_HALF_USE_LOOKUP_TABLE": False,
            "IMATH_HAVE_LARGE_STACK": False,
            "IMATH_USE_NOEXCEPT": True,
            # Built statically into the engine; nothing crosses a library boundary.
            "IMATH_ENABLE_API_VISIBILITY": False,
        },
    )
    shutil.copyfile(os.path.join(src, "LICENSE.md"), os.path.join(dst, "LICENSE.md"))


def vendor_yaml_cpp(src):
    dst = os.path.join(THIRDPARTY, "yaml-cpp")
    rmtree(dst)
    print("  yaml-cpp ->", os.path.relpath(dst, GODOT_ROOT))

    copy_tree(os.path.join(src, "include"), os.path.join(dst, "include"), suffixes=(".h",))
    copy_tree(
        os.path.join(src, "src"),
        os.path.join(dst, "src"),
        skip_dirs={"contrib"},
        suffixes=(".h", ".cpp"),
    )
    shutil.copyfile(os.path.join(src, "LICENSE"), os.path.join(dst, "LICENSE"))


def vendor_pystring(src):
    dst = os.path.join(THIRDPARTY, "pystring")
    rmtree(dst)
    print("  pystring ->", os.path.relpath(dst, GODOT_ROOT))
    os.makedirs(dst, exist_ok=True)
    for name in ("pystring.h", "pystring.cpp", "LICENSE"):
        shutil.copyfile(os.path.join(src, name), os.path.join(dst, name))


def vendor_expat(src):
    dst = os.path.join(THIRDPARTY, "expat")
    rmtree(dst)
    print("  expat ->", os.path.relpath(dst, GODOT_ROOT))

    lib_src = os.path.join(src, "lib")
    os.makedirs(os.path.join(dst, "lib"), exist_ok=True)
    for name in sorted(os.listdir(lib_src)):
        if name.endswith((".c", ".h")):
            shutil.copyfile(os.path.join(lib_src, name), os.path.join(dst, "lib", name))

    write(os.path.join(dst, "lib", "expat_config.h"), EXPAT_CONFIG_H.format(version=EXPAT_VERSION))
    shutil.copyfile(os.path.join(src, "COPYING"), os.path.join(dst, "COPYING"))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--src", help="directory holding the already-extracted upstream trees")
    args = parser.parse_args()

    if args.src:
        source_dir = os.path.abspath(args.src)
        download_and_extract(source_dir)
        run(source_dir)
    else:
        with tempfile.TemporaryDirectory(prefix="ocio-vendor-") as tmp:
            download_and_extract(tmp)
            run(tmp)


def run(source_dir):
    print("Vendoring into", THIRDPARTY)
    vendor_opencolorio(os.path.join(source_dir, "OpenColorIO-%s" % OCIO_VERSION))
    vendor_imath(os.path.join(source_dir, "Imath-%s" % IMATH_VERSION))
    vendor_yaml_cpp(os.path.join(source_dir, "yaml-cpp-%s" % YAML_CPP_VERSION))
    vendor_pystring(os.path.join(source_dir, "pystring-%s" % PYSTRING_VERSION))
    vendor_expat(os.path.join(source_dir, "expat-%s" % EXPAT_VERSION))
    print("Done. Remember to update thirdparty/README.md and COPYRIGHT.txt if versions changed.")


if __name__ == "__main__":
    main()
